### ISSUE TITLE
Make a semver release for plugin-hbs

### ISSUE THREAD

**Issue by paulfalgout** [davis/plugin-hbs#1]
"github:davis/plugin-hbs@master": is scary   With `@x.y.z` there's a clearer understanding of what could possibly break.

**Comment by davis** [comment]
good idea. thanks!

**Comment by davis** [comment]
Here is the release: https://github.com/davis/plugin-hbs/releases
I've also submitted a pull-request to the jspm registry, so that you'll be able to install it using `jspm i hbs`
