### ISSUE TITLE
Bundling broken

### ISSUE THREAD

**Issue by MeoMix** [davis/plugin-hbs#5]
The recent changes broke bundling. No template is inlined at all during bundling now :( :-1:

**Comment by milkshakeuk** [comment]
I have verified this, I wonder why the bundling doesn't like instantiate but it works unbundled?

**Comment by davis** [comment]
Okay, I have a fix for this!
Just doing some last testing so I'm sure it's fixed this time! :)

**Comment by davis** [comment]
Fixed. Need to use `translate` for plugins so that it works during bundling.

**Comment by MeoMix** [comment]
Interesting. I would've not guessed that solution at all. I looked at the regular css importer and it doesn't use translate at all. It calls "bundle." Regardless, good to see it working again I'll give it a spin in a min
