### ISSUE TITLE
It works just with marionette?

### ISSUE THREAD

**Issue by luisfmsouza** [davis/plugin-hbs#6]
Does this plugin loader works without marionette?

**Comment by davis** [comment]
I haven't tested it outside of marionette, but it should work elsewhere - is it not working for you?

**Comment by luisfmsouza** [comment]
It wasn't, but after some troubles I figure out how to make it work.

Do you think is it a good idea add an example on README.md?

**Comment by davis** [comment]
Could you send me a way you got it to work? I would be glad to add non-marionette examples to the readme! thanks!

**Comment by luisfmsouza** [comment]
@davis here is how I did:

```
import template from './template.hbs!';
import data from './data.json!';

var html = template(data);

$('#content').html(html);
```

**Comment by davis** [comment]
I'll add this example to the readme. Thanks!
